---
name: "k3s-etc"
services:
  k3s-etc:
    tty: true
    privileged: true
    cgroup: host
    # Start the Devcontainer from a pre-built image from a docker repository
    image: ghcr.io/star3am/k3s-etc:latest
    # Build the container from the Dockerfile before we run it
    # build:
    #   context: ../../
    #   dockerfile: .devcontainer/k3s-etc/Dockerfile
    network_mode: "bridge"
    tmpfs:
      - /var/lib/docker:mode=0777,dev,size=15g,suid,exec # docker
      - /var/lib/rancher:mode=0777,dev,size=15g,suid,exec # k3s
      - /run
    ports:
      - "16443:16443" # k3s kubernetes cluster api
      - "18001:18001" # kubernetes dashboard
      - "18002:18002" # helm dashboard
    volumes:
      # Mounts the project folder into the container
      - "../../:/app"
      # Needed for systemd
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      # Mount your ~/.ssh folder into the container
      # for Authenticating to Github
      - "~/.ssh:/home/ubuntu/.ssh"
      # For GPG Auth to Github
      - "~/.gnupg:/home/ubuntu/.gnupg"
      # Add your .aws or .azure or .kube directories here
      # - "$AZURE_CONFIG_DIR:/home/ubuntu/.azure"
    working_dir: "/app"
    environment:
      - GPG_TTY=/dev/pts/1
      - KUBECONFIG=/home/ubuntu/.kube/config
